name: SSH into EC2 Behind VPN

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get install -y openvpn
      # - name: Set Up VPN Configuration and Credentials
      #   run: |
      #     echo "${{ secrets.VPN_CONFIG }}" > vpn_config.ovpn
      #     echo "${{ secrets.VPN_USERNAME }}" > vpn_username.txt
      #     echo "${{ secrets.VPN_PASSWORD }}" > vpn_password.txt
      #     echo "${{ secrets.VPN_USERNAME }}" > vpn_credentials.txt
      #     echo "${{ secrets.VPN_PASSWORD }}" >> vpn_credentials.txt
      #     chmod 600 vpn_credentials.txt
      # - name: Connect to VPN
      #   run: |
      #     sudo openvpn --config vpn_config.ovpn --auth-user-pass vpn_credentials.txt --daemon
      #     sleep 10
      #     sudo cat /var/log/syslog | grep openvpn
      - name: Connect to VPN
        env:
         VPN_USERNAME: ${{ secrets.VPN_USERNAME }}
         VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
        run: |
          echo "$VPN_USERNAME" > vpn_creds.txt
          echo "$VPN_PASSWORD" >> vpn_creds.txt
          chmod 600 vpn_creds.txt
          sudo openvpn --config vpn_config.ovpn --auth-user-pass vpn_creds.txt --daemon --verb 4
          sleep 30

          if pgrep openvpn > /dev/null
          then
           echo "OpenVPN process is running"
           ip addr show
          else
           echo "OpenVPN process is not running"
          sudo cat /var/log/syslog | grep openvpn
          exit 1
          fi

          rm vpn_creds.txt

      - name: SSH into EC2 and Create Folder
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: mkdir -p ~/new_folder

      - name: Clean Up VPN Configuration
        run: |
          # Optional cleanup commands, if any
