name: Create and Print File

on:
  workflow_dispatch:

jobs:
  create_and_print_file:
    runs-on: ubuntu-latest

    steps:
      - name: Create a File and Write to It
        run: |
          echo "Hello, this is a test message!" > testfile.txt

      - name: Print the File Contents
        run: |
          cat testfile.txt
