name: SSH into EC2 Behind VPN

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect OpenVPN
        uses: swissbuechi/action-openvpn-client@v1.0.0
        with:
          host: ${{ secrets.VPN_HOST }}             # VPN server address
          username: ${{ secrets.VPN_USERNAME }}     # VPN username
          password: ${{ secrets.VPN_PASSWORD }}     # VPN password
          # Optional parameters
          logs: true                               # Optional: enable logging
          # dns-server: ${{ secrets.DNS_SERVER }}    # Optional: DNS server if needed
          ovpn-config: ${{ secrets.VPN_CONFIG }}  # Optional: VPN configuration file content
          test-ping-ip-host: 8.8.8.8               # Optional: IP to test the connection
          test-dns-host: example.com               # Optional: DNS to test the connection
          port: 1194                               # Optional: port for the VPN connection
          # otp-hex: ${{ secrets.OTP_HEX }}          # Optional: OTP hex if needed
          # otp-timezone: ${{ secrets.OTP_TIMEZONE }} # Optional: OTP timezone
          # ca: ${{ secrets.CA_CERTIFICATE }}        # Optional: CA certificate
          # cert: ${{ secrets.CLIENT_CERTIFICATE }}  # Optional: Client certificate
          # cert-key: ${{ secrets.CLIENT_KEY }}      # Optional: Client key

      - name: SSH into EC2 and Create Folder
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: mkdir -p ~/new_folder

      - name: Clean Up VPN Configuration
        run: |
          # Optional cleanup commands, if any
