name: Create and Print File

on:
  workflow_dispatch:

jobs:
  create_and_print_file:
    runs-on: ubuntu-latest

    steps:
      - name: Create a File and Write to It
        run: |
          echo "${{ secrets.VPN_CONFIG }}" > vpn_config.ovpn
          echo "${{ secrets.VPN_USERNAME }}" > vpn_username.txt
          echo "${{ secrets.VPN_PASSWORD }}" > vpn_password.txt
          echo "${{ secrets.VPN_USERNAME }}" > vpn_credentials.txt
          echo "${{ secrets.VPN_PASSWORD }}" >> vpn_credentials.txt

      - name: Print the File Contents
        run: |
          cat vpn_credentials.txt
